// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/openshift/assisted-service/internal/controller/controllers (interfaces: SpokeClientCache)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -package=controllers -destination=mock_spoke_client_cache.go . SpokeClientCache
//

// Package controllers is a generated GoMock package.
package controllers

import (
	reflect "reflect"

	spoke_k8s_client "github.com/openshift/assisted-service/internal/spoke_k8s_client"
	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/core/v1"
)

// MockSpokeClientCache is a mock of SpokeClientCache interface.
type MockSpokeClientCache struct {
	ctrl     *gomock.Controller
	recorder *MockSpokeClientCacheMockRecorder
	isgomock struct{}
}

// MockSpokeClientCacheMockRecorder is the mock recorder for MockSpokeClientCache.
type MockSpokeClientCacheMockRecorder struct {
	mock *MockSpokeClientCache
}

// NewMockSpokeClientCache creates a new mock instance.
func NewMockSpokeClientCache(ctrl *gomock.Controller) *MockSpokeClientCache {
	mock := &MockSpokeClientCache{ctrl: ctrl}
	mock.recorder = &MockSpokeClientCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpokeClientCache) EXPECT() *MockSpokeClientCacheMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockSpokeClientCache) Get(secret *v1.Secret) (spoke_k8s_client.SpokeK8sClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", secret)
	ret0, _ := ret[0].(spoke_k8s_client.SpokeK8sClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSpokeClientCacheMockRecorder) Get(secret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSpokeClientCache)(nil).Get), secret)
}
